import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const out=new URL('./outputs/01a087f4/',import.meta.url);
const [{page,rows}]=JSON.parse(await fs.readFile(new URL('extracted.json',out),'utf8'));
const wb=Workbook.create();
const s=wb.worksheets.add(`PDF_p${String(page).padStart(3,'0')}`);
s.showGridLines=false;
s.getRange('A1:E12').format.font={name:'Arial',size:10,color:'#18263B'};
s.mergeCells('A1:E1');s.getRange('A1').values=[['Table conversion sample']];
s.getRange('A1').format.font={name:'Arial',size:16,bold:true};
s.mergeCells('A2:E2');s.getRange('A2').values=[['Fictitious records. Source: source.pdf, page 1.']];
s.getRange('A2').format.font={name:'Arial',size:10,color:'#526276'};
function amount(v){if(v==='')return null;return Number(v.replaceAll(',','').replace('(','-').replace(')',''));}
const typed=[rows[0],...rows.slice(1).map(r=>[r[0],r[1],Number(r[2]),amount(r[3]),Number(r[4].replace('%',''))/100])];
s.getRange('A4:E11').values=typed;
s.getRange('A4:E11').format.rowHeight=29;
s.getRange('A4:E11').format.verticalAlignment='center';
s.getRange('A4:E11').format.borders={preset:'all',style:'thin',color:'#B8C2D0'};
s.getRange('A4:E4').format={fill:'#18263B',font:{name:'Arial',size:10,bold:true,color:'#FFFFFF'},horizontalAlignment:'center'};
for(const [col,width]of [['A',94],['B',198],['C',80],['D',150],['E',126]])s.getRange(`${col}1:${col}12`).format.columnWidthPx=width;
s.getRange('A5:A11').setNumberFormat('000000');
s.getRange('C5:C11').setNumberFormat('0');
s.getRange('D5:D11').setNumberFormat('#,##0.00;-#,##0.00;0.00');
s.getRange('D6').setNumberFormat('#,##0.00;(#,##0.00);0.00');
s.getRange('E5:E11').setNumberFormat('0.00%');
s.mergeCells('A12:E12');s.getRange('A12').values=[['Blank amount is intentional. References retain six digits.']];
s.getRange('A12').format.font={name:'Arial',size:10,color:'#526276'};
wb.recalculate();
const preview=await wb.render({sheetName:s.name,range:'A1:E12',scale:1.5,format:'png'});
await fs.writeFile(new URL('excel-preview.png',out),new Uint8Array(await preview.arrayBuffer()));
const xlsx=await SpreadsheetFile.exportXlsx(wb);await xlsx.save(new URL('converted.xlsx',out).pathname);
console.log((await wb.inspect({kind:'region',sheetId:s.name,range:'A4:E11',maxChars:1800})).ndjson);
